---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default-client
    run_list:
      - recipe[postgresql_solo::client]
  
  - name: default-master
    run_list:
      - recipe[postgresql_solo::master]
