---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: 'test/nodes'
  environments_path: 'test/environments'
  client_rb:
    environment: staging

platforms:
  - name: ubuntu-16.04

suites:
  - name: default-client
    run_list:
      - recipe[postgresql_solo::client]
  
  - name: default-master
    run_list:
      - recipe[postgresql_solo::master]
